### ISSUE TITLE
Billing Fields are placed twice on the checkout page

### ISSUE THREAD

**Issue by DJTim** [myparcelbe/woocommerce#54] opened 2018-12-16 19:24 UTC
Billing fields layout and fields are wrong, they appear twice on the page and don't match configuration of StoreFront.

WordPress 5.0.1
WooCommerce 3.5.2
StoreFront 2.4.2

MyParcel disabled:
![screenshot 2018-12-16 20 21 14](https://user-images.githubusercontent.com/4507858/50057833-275ecd00-0170-11e9-8ebd-bfb85a99e501.png)

MyParcel enabled:
![screenshot 2018-12-16 20 12 31](https://user-images.githubusercontent.com/4507858/50057815-f8485b80-016f-11e9-8226-711a341f66b8.png)

**Comment by RichardPerdaan** [comment] 2018-12-17 07:04
Hi @DJTim,

Thank you for your message. If you click on the link below, a zip file will be downloaded.
[Zip file click here](https://github.com/myparcelbe/woocommerce/archive/fix-checkout-fields.zip)

This is a version of the plugin that is not live yet. Would you install this version and see if the problem is still there?

**Comment by DJTim** [comment] 2018-12-26 15:03
Issue still exists:

![screenshot 2018-12-26 16 02 24](https://user-images.githubusercontent.com/4507858/50449445-c2e9fd80-0927-11e9-98e8-09754ff6e82a.png)

**Comment by RichardPerdaan** [comment] 2018-12-27 16:02
this problem is because the address fields need a priority. Through this [link](https://github.com/myparcelbe/woocommerce/blob/d466c4b7f1fba1c6ef67a1c4c176e82bc337549e/includes/class-wcmp-bepostcode-fields.php#L213-L232) you can see the solution.

This will be included with the next update.

**Closed** 2019-06-27 13:53 UTC
Labels: Next version
